# Generated by Django 5.1.1 on 2024-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('fuel', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], default='petrol', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fuel Price',
                'verbose_name_plural': 'Fuel Prices',
                'ordering': ['state', 'city'],
                'unique_together': {('state', 'city', 'created_at')},
            },
        ),
    ]
