# Generated by Django 5.1.1 on 2024-09-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(default='petrol', max_length=50, verbose_name='Fuel')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('date', models.DateField(verbose_name='Date')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_prices', to='crawler.location')),
            ],
            options={
                'verbose_name_plural': 'Fuel Prices',
                'ordering': ['-date'],
                'unique_together': {('city', 'fuel', 'date')},
            },
        ),
    ]
