# Generated by Django 5.1.1 on 2024-09-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelprice',
            options={'ordering': ['-date'], 'verbose_name': 'Fuel Price', 'verbose_name_plural': 'Fuel Prices'},
        ),
        migrations.RenameField(
            model_name='fuelprice',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='fuelprice',
            unique_together={('state', 'city', 'date')},
        ),
    ]
